import type { Metadata } from 'next';

import Providers from './Providers';
import Footer from './components/Footer';
import NavBar from './components/NavBar';
import './styles/global.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className='h-full'>
			<body className='flex h-full flex-col'>
				<header className='sticky top-0 z-50'>
					<NavBar />
				</header>
				<main className='h-full flex-1'>
					<Providers>{children}</Providers>
				</main>
				<Footer />
			</body>
		</html>
	);
}
