import type { Metadata } from 'next';

import Footer from './components/Footer';
import { NavBar } from './components/NavBar';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<NavBar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
